import { UserRole } from "./database";

export enum Permission {
    // Reservations
    RESERVATION_VIEW = "RESERVATION_VIEW",
    RESERVATION_CREATE = "RESERVATION_CREATE",
    RESERVATION_EDIT = "RESERVATION_EDIT",
    RESERVATION_CANCEL = "RESERVATION_CANCEL",
    RESERVATION_CHECKIN = "RESERVATION_CHECKIN",
    RESERVATION_CHECKOUT = "RESERVATION_CHECKOUT",
    RESERVATION_NOSHOW = "RESERVATION_NOSHOW",
    RESERVATION_PRICE_MODIFY = "RESERVATION_PRICE_MODIFY",
    RESERVATION_STATUS_UPDATE = "RESERVATION_STATUS_UPDATE",
    RESERVATION_STATUS_CHECKIN = "RESERVATION_STATUS_CHECKIN",
    RESERVATION_STATUS_CHECKOUT = "RESERVATION_STATUS_CHECKOUT",
    RESERVATION_STATUS_CANCEL = "RESERVATION_STATUS_CANCEL",
    RESERVATION_STATUS_NO_SHOW = "RESERVATION_STATUS_NO_SHOW",
    RESERVATION_STATUS_UNDO_CHECKOUT = "RESERVATION_STATUS_UNDO_CHECKOUT",
    RESERVATION_STATUS_REINSTATE = "RESERVATION_STATUS_REINSTATE",

    // Folio & Finance
    FOLIO_VIEW = "FOLIO_VIEW",
    FINANCE_PAYMENT_ADD = "FINANCE_PAYMENT_ADD",
    FINANCE_CHARGE_ADD = "FINANCE_CHARGE_ADD",
    FINANCE_DISCOUNT_APPLY = "FINANCE_DISCOUNT_APPLY",
    FINANCE_REFUND_ISSUE = "FINANCE_REFUND_ISSUE",
    FINANCE_ENTRY_DELETE = "FINANCE_ENTRY_DELETE",
    FINANCE_REVERSE = "FINANCE_REVERSE",
    FINANCE_REPORT_EXPORT = "FINANCE_REPORT_EXPORT",

    // Reports
    REPORT_VIEW = "REPORT_VIEW",
    REPORT_EXPORT = "REPORT_EXPORT",

    // System
    SYSTEM_USERS_MANAGE = "SYSTEM_USERS_MANAGE",
    SYSTEM_SETTINGS_HOTEL = "SYSTEM_SETTINGS_HOTEL",
    SYSTEM_SETTINGS_CURRENCY = "SYSTEM_SETTINGS_CURRENCY",
    SYSTEM_DAY_CLOSE = "SYSTEM_DAY_CLOSE",
    SYSTEM_SETTINGS_MODIFY = "SYSTEM_SETTINGS_MODIFY",

    // Advanced Hotel Configuration
    HOTEL_CATALOG_VIEW = "HOTEL_CATALOG_VIEW",
    HOTEL_CATALOG_MANAGE = "HOTEL_CATALOG_MANAGE",
    HOTEL_PRICING_VIEW = "HOTEL_PRICING_VIEW",
    HOTEL_PRICING_MANAGE = "HOTEL_PRICING_MANAGE",
    HOTEL_INVENTORY_VIEW = "HOTEL_INVENTORY_VIEW",
    HOTEL_INVENTORY_MANAGE = "HOTEL_INVENTORY_MANAGE",
    HOTEL_SOURCES_VIEW = "HOTEL_SOURCES_VIEW",
    HOTEL_SOURCES_MANAGE = "HOTEL_SOURCES_MANAGE",

    // Auto No-Show Engine
    RESERVATION_NO_SHOW_MARK = "RESERVATION_NO_SHOW_MARK",
    RESERVATION_NO_SHOW_UNDO = "RESERVATION_NO_SHOW_UNDO",
    RESERVATION_NO_SHOW_ENGINE_CONFIGURE = "RESERVATION_NO_SHOW_ENGINE_CONFIGURE",

    // Room Allocation Engine
    RESERVATION_ROOM_ASSIGN_MANUAL = "RESERVATION_ROOM_ASSIGN_MANUAL",
    RESERVATION_ROOM_ASSIGN_AUTO = "RESERVATION_ROOM_ASSIGN_AUTO",
    RESERVATION_ROOM_ASSIGN_BULK = "RESERVATION_ROOM_ASSIGN_BULK",
    RESERVATION_ROOM_UPGRADE_SUGGEST = "RESERVATION_ROOM_UPGRADE_SUGGEST",

    // Smart Operations Dashboard
    DASHBOARD_OPS_VIEW = "DASHBOARD_OPS_VIEW",
}

export type RolePermissions = {
    [key in UserRole]?: Permission[];
};

export const DEFAULT_ROLE_PERMISSIONS: RolePermissions = {
    [UserRole.SUPER_ADMIN]: Object.values(Permission),
    [UserRole.ADMIN]: Object.values(Permission),
    [UserRole.RECEPTION]: [
        Permission.RESERVATION_VIEW,
        Permission.RESERVATION_CREATE,
        Permission.RESERVATION_EDIT,
        Permission.RESERVATION_CANCEL,
        Permission.RESERVATION_CHECKIN,
        Permission.RESERVATION_CHECKOUT,
        Permission.RESERVATION_NOSHOW,
        Permission.RESERVATION_STATUS_CHECKIN,
        Permission.RESERVATION_STATUS_CHECKOUT,
        Permission.RESERVATION_STATUS_CANCEL,
        Permission.RESERVATION_STATUS_NO_SHOW,
        Permission.FOLIO_VIEW,
        Permission.FINANCE_PAYMENT_ADD,
        Permission.RESERVATION_NO_SHOW_MARK,
        Permission.RESERVATION_ROOM_ASSIGN_MANUAL,
        Permission.RESERVATION_ROOM_ASSIGN_AUTO,
        Permission.DASHBOARD_OPS_VIEW,
    ],
    [UserRole.HOUSEKEEPING]: [
        Permission.RESERVATION_VIEW,
        Permission.DASHBOARD_OPS_VIEW,
    ],
    [UserRole.FINANCE]: [
        Permission.FOLIO_VIEW,
        Permission.FINANCE_PAYMENT_ADD,
        Permission.FINANCE_CHARGE_ADD,
        Permission.FINANCE_DISCOUNT_APPLY,
        Permission.FINANCE_REFUND_ISSUE,
        Permission.FINANCE_REVERSE,
        Permission.FINANCE_REPORT_EXPORT,
        Permission.REPORT_VIEW,
        Permission.REPORT_EXPORT,
    ],
    [UserRole.NIGHT_AUDIT]: [
        Permission.RESERVATION_VIEW,
        Permission.FOLIO_VIEW,
        Permission.REPORT_VIEW,
        Permission.SYSTEM_DAY_CLOSE,
        Permission.DASHBOARD_OPS_VIEW,
    ],
    [UserRole.MANAGER]: [
        Permission.RESERVATION_VIEW,
        Permission.RESERVATION_CREATE,
        Permission.RESERVATION_EDIT,
        Permission.RESERVATION_CANCEL,
        Permission.RESERVATION_CHECKIN,
        Permission.RESERVATION_CHECKOUT,
        Permission.RESERVATION_NOSHOW,
        Permission.RESERVATION_STATUS_UPDATE,
        Permission.RESERVATION_STATUS_CHECKIN,
        Permission.RESERVATION_STATUS_CHECKOUT,
        Permission.RESERVATION_STATUS_CANCEL,
        Permission.RESERVATION_STATUS_NO_SHOW,
        Permission.RESERVATION_STATUS_UNDO_CHECKOUT,
        Permission.RESERVATION_STATUS_REINSTATE,
        Permission.FOLIO_VIEW,
        Permission.FINANCE_PAYMENT_ADD,
        Permission.REPORT_VIEW,
        Permission.HOTEL_CATALOG_VIEW,
        Permission.HOTEL_PRICING_VIEW,
        Permission.HOTEL_INVENTORY_VIEW,
        Permission.HOTEL_SOURCES_VIEW,
        Permission.RESERVATION_NO_SHOW_MARK,
        Permission.RESERVATION_NO_SHOW_UNDO,
        Permission.RESERVATION_ROOM_ASSIGN_MANUAL,
        Permission.RESERVATION_ROOM_ASSIGN_AUTO,
        Permission.RESERVATION_ROOM_ASSIGN_BULK,
        Permission.RESERVATION_ROOM_UPGRADE_SUGGEST,
    ],
    [UserRole.PERSONEL]: [
        Permission.RESERVATION_VIEW,
        Permission.FOLIO_VIEW,
    ],
};

