-- ============================================================
-- 20260305100000_night_audit_engine.sql
-- Module: Night Audit Engine (Enterprise)
-- Purpose: Automated nightly room charge posting, daily metrics,
--          business date management, and day close.
-- ============================================================

-- ============================================================
-- 1. HOTEL BUSINESS DATES TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.hotel_business_dates (
    id              UUID PRIMARY KEY DEFAULT extensions.uuid_generate_v4(),
    hotel_id        UUID NOT NULL REFERENCES public.hotels(id) ON DELETE CASCADE,
    business_date   DATE NOT NULL DEFAULT CURRENT_DATE,
    status          TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed')),
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uq_hotel_business_date UNIQUE (hotel_id)
);

COMMENT ON TABLE public.hotel_business_dates IS 'Tracks the current open business date per hotel. Night audit advances this date by +1.';

-- ============================================================
-- 2. DAILY HOTEL STATS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.daily_hotel_stats (
    id              UUID PRIMARY KEY DEFAULT extensions.uuid_generate_v4(),
    hotel_id        UUID NOT NULL REFERENCES public.hotels(id) ON DELETE CASCADE,
    date            DATE NOT NULL,

    -- Occupancy
    rooms_available INTEGER NOT NULL DEFAULT 0,
    rooms_sold      INTEGER NOT NULL DEFAULT 0,
    occupancy_rate  NUMERIC(5, 2) NOT NULL DEFAULT 0,

    -- Revenue
    revenue_room    NUMERIC(12, 2) NOT NULL DEFAULT 0,
    revenue_total   NUMERIC(12, 2) NOT NULL DEFAULT 0,

    -- KPIs
    adr             NUMERIC(12, 2) NOT NULL DEFAULT 0,
    revpar          NUMERIC(12, 2) NOT NULL DEFAULT 0,

    created_at      TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT uq_hotel_daily_stats UNIQUE (hotel_id, date)
);

COMMENT ON TABLE public.daily_hotel_stats IS 'Daily aggregated hotel performance metrics generated by Night Audit Engine.';

-- ============================================================
-- 3. INDEXES
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_hotel_business_dates_hotel_id
    ON public.hotel_business_dates(hotel_id);

CREATE INDEX IF NOT EXISTS idx_daily_hotel_stats_hotel_date
    ON public.daily_hotel_stats(hotel_id, date DESC);

-- Index for double-posting guard (plain column index, no function expression)
CREATE INDEX IF NOT EXISTS idx_folio_room_charge_daily
    ON public.folio_transactions(reservation_id, type, description, created_at);

-- ============================================================
-- 4. RLS POLICIES
-- ============================================================
ALTER TABLE public.hotel_business_dates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_hotel_stats    ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "hotel_business_dates_hotel_isolation" ON public.hotel_business_dates;
CREATE POLICY "hotel_business_dates_hotel_isolation"
ON public.hotel_business_dates FOR ALL
USING (hotel_id IN (SELECT hotel_id FROM public.users WHERE id = auth.uid()));

DROP POLICY IF EXISTS "daily_hotel_stats_hotel_isolation" ON public.daily_hotel_stats;
CREATE POLICY "daily_hotel_stats_hotel_isolation"
ON public.daily_hotel_stats FOR ALL
USING (hotel_id IN (SELECT hotel_id FROM public.users WHERE id = auth.uid()));

-- ============================================================
-- 5. HELPER: INITIALIZE BUSINESS DATE FOR HOTEL
-- ============================================================
CREATE OR REPLACE FUNCTION public.initialize_hotel_business_date(
    p_hotel_id UUID,
    p_start_date DATE DEFAULT CURRENT_DATE
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    INSERT INTO public.hotel_business_dates (hotel_id, business_date, status)
    VALUES (p_hotel_id, p_start_date, 'open')
    ON CONFLICT (hotel_id) DO NOTHING;
END;
$$;

-- ============================================================
-- 6. MAIN RPC: run_night_audit(hotel_id)
-- ============================================================
CREATE OR REPLACE FUNCTION public.run_night_audit(
    p_hotel_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_business_date     DATE;
    v_next_date         DATE;
    v_rooms_available   INTEGER;
    v_rooms_sold        INTEGER;
    v_occupancy_rate    NUMERIC(5, 2);
    v_revenue_room      NUMERIC(12, 2);
    v_revenue_total     NUMERIC(12, 2);
    v_adr               NUMERIC(12, 2);
    v_revpar            NUMERIC(12, 2);
    v_charges_posted    INTEGER := 0;
    v_res               RECORD;
    v_already_charged   BOOLEAN;
BEGIN
    -- ------------------------------------
    -- STEP 1: Get or initialize business date
    -- ------------------------------------
    SELECT business_date
    INTO v_business_date
    FROM public.hotel_business_dates
    WHERE hotel_id = p_hotel_id;

    IF NOT FOUND THEN
        -- First run: initialize to today
        v_business_date := CURRENT_DATE;
        INSERT INTO public.hotel_business_dates (hotel_id, business_date, status)
        VALUES (p_hotel_id, v_business_date, 'open');
    END IF;

    v_next_date := v_business_date + INTERVAL '1 day';

    -- ------------------------------------
    -- STEP 2: Post daily room charges
    -- ------------------------------------
    FOR v_res IN
        SELECT
            r.id AS reservation_id,
            r.hotel_id,
            r.guest_id,
            COALESCE(r.nightly_rate, 0) AS daily_rate
        FROM public.reservations r
        WHERE r.hotel_id = p_hotel_id
          AND r.status = 'checked_in'
          AND (r.check_in_date AT TIME ZONE 'UTC')::date <= v_business_date
          AND (r.check_out_date AT TIME ZONE 'UTC')::date > v_business_date
    LOOP
        -- Double-posting guard: check by business_date stored in metadata
        SELECT EXISTS (
            SELECT 1
            FROM public.folio_transactions ft
            WHERE ft.reservation_id = v_res.reservation_id
              AND ft.type = 'room_charge'
              AND ft.description = 'Daily room charge'
              AND (ft.metadata->>'business_date')::date = v_business_date
        ) INTO v_already_charged;

        IF NOT v_already_charged THEN
            INSERT INTO public.folio_transactions (
                hotel_id,
                reservation_id,
                guest_id,
                type,
                amount,
                description,
                source,
                metadata
            ) VALUES (
                v_res.hotel_id,
                v_res.reservation_id,
                v_res.guest_id,
                'room_charge',
                v_res.daily_rate,
                'Daily room charge',
                'system',
                jsonb_build_object(
                    'business_date', v_business_date,
                    'source', 'night_audit'
                )
            );
            v_charges_posted := v_charges_posted + 1;
        END IF;
    END LOOP;

    -- Log room charges
    INSERT INTO public.activity_logs (hotel_id, action, details, module)
    VALUES (
        p_hotel_id,
        'room_charges_posted',
        jsonb_build_object(
            'business_date', v_business_date,
            'charges_posted', v_charges_posted,
            'source', 'system'
        ),
        'NIGHT_AUDIT'
    );

    -- ------------------------------------
    -- STEP 3: Calculate occupancy metrics
    -- ------------------------------------
    SELECT COUNT(*) INTO v_rooms_available
    FROM public.rooms
    WHERE hotel_id = p_hotel_id
      AND status NOT IN ('OOO');

    SELECT COUNT(*) INTO v_rooms_sold
    FROM public.reservations
    WHERE hotel_id = p_hotel_id
      AND status = 'checked_in'
      AND (check_in_date AT TIME ZONE 'UTC')::date <= v_business_date
      AND (check_out_date AT TIME ZONE 'UTC')::date > v_business_date;

    IF v_rooms_available > 0 THEN
        v_occupancy_rate := ROUND((v_rooms_sold::NUMERIC / v_rooms_available::NUMERIC) * 100, 2);
    ELSE
        v_occupancy_rate := 0;
    END IF;

    -- ------------------------------------
    -- STEP 4: Calculate revenue metrics
    -- ------------------------------------
    SELECT
        COALESCE(SUM(CASE WHEN ft.type = 'room_charge' THEN ft.amount ELSE 0 END), 0),
        COALESCE(SUM(ft.amount), 0)
    INTO v_revenue_room, v_revenue_total
    FROM public.folio_transactions ft
    WHERE ft.hotel_id = p_hotel_id
      AND (ft.metadata->>'business_date')::date = v_business_date
      AND ft.type IN ('room_charge', 'service_charge', 'tax');

    -- ADR: Average Daily Rate = room_revenue / rooms_sold
    IF v_rooms_sold > 0 THEN
        v_adr := ROUND(v_revenue_room / v_rooms_sold, 2);
    ELSE
        v_adr := 0;
    END IF;

    -- RevPAR: Revenue Per Available Room = room_revenue / rooms_available
    IF v_rooms_available > 0 THEN
        v_revpar := ROUND(v_revenue_room / v_rooms_available, 2);
    ELSE
        v_revpar := 0;
    END IF;

    -- ------------------------------------
    -- STEP 5: Write daily stats (upsert)
    -- ------------------------------------
    INSERT INTO public.daily_hotel_stats (
        hotel_id, date,
        rooms_available, rooms_sold, occupancy_rate,
        revenue_room, revenue_total,
        adr, revpar
    ) VALUES (
        p_hotel_id, v_business_date,
        v_rooms_available, v_rooms_sold, v_occupancy_rate,
        v_revenue_room, v_revenue_total,
        v_adr, v_revpar
    )
    ON CONFLICT (hotel_id, date) DO UPDATE SET
        rooms_available = EXCLUDED.rooms_available,
        rooms_sold      = EXCLUDED.rooms_sold,
        occupancy_rate  = EXCLUDED.occupancy_rate,
        revenue_room    = EXCLUDED.revenue_room,
        revenue_total   = EXCLUDED.revenue_total,
        adr             = EXCLUDED.adr,
        revpar          = EXCLUDED.revpar;

    -- Log daily stats generation
    INSERT INTO public.activity_logs (hotel_id, action, details, module)
    VALUES (
        p_hotel_id,
        'daily_stats_generated',
        jsonb_build_object(
            'business_date', v_business_date,
            'rooms_available', v_rooms_available,
            'rooms_sold', v_rooms_sold,
            'occupancy_rate', v_occupancy_rate,
            'revenue_room', v_revenue_room,
            'adr', v_adr,
            'revpar', v_revpar,
            'source', 'system'
        ),
        'NIGHT_AUDIT'
    );

    -- ------------------------------------
    -- STEP 6: Advance business date +1
    -- ------------------------------------
    UPDATE public.hotel_business_dates
    SET business_date = v_next_date,
        status = 'open'
    WHERE hotel_id = p_hotel_id;

    -- ------------------------------------
    -- STEP 7: Log audit run
    -- ------------------------------------
    INSERT INTO public.activity_logs (hotel_id, action, details, module)
    VALUES (
        p_hotel_id,
        'night_audit_run',
        jsonb_build_object(
            'business_date_closed', v_business_date,
            'new_business_date', v_next_date,
            'charges_posted', v_charges_posted,
            'rooms_sold', v_rooms_sold,
            'occupancy_rate', v_occupancy_rate,
            'revenue_room', v_revenue_room,
            'adr', v_adr,
            'revpar', v_revpar,
            'source', 'system',
            'run_at', NOW()
        ),
        'NIGHT_AUDIT'
    );

    RETURN jsonb_build_object(
        'success', true,
        'business_date_closed', v_business_date,
        'new_business_date', v_next_date,
        'charges_posted', v_charges_posted,
        'rooms_available', v_rooms_available,
        'rooms_sold', v_rooms_sold,
        'occupancy_rate', v_occupancy_rate,
        'revenue_room', v_revenue_room,
        'revenue_total', v_revenue_total,
        'adr', v_adr,
        'revpar', v_revpar
    );
END;
$$;

-- ============================================================
-- 7. RPC: get_night_audit_status(hotel_id)
-- Returns current business date + latest stats for UI card
-- ============================================================
CREATE OR REPLACE FUNCTION public.get_night_audit_status(
    p_hotel_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_business_date     DATE;
    v_last_audit_at     TIMESTAMPTZ;
    v_stats             RECORD;
    v_today_revenue     NUMERIC(12, 2) := 0;
    v_occupancy_rate    NUMERIC(5, 2) := 0;
BEGIN
    -- Get business date
    SELECT business_date INTO v_business_date
    FROM public.hotel_business_dates
    WHERE hotel_id = p_hotel_id;

    IF NOT FOUND THEN
        v_business_date := CURRENT_DATE;
    END IF;

    -- Get last audit timestamp from activity_logs
    SELECT created_at INTO v_last_audit_at
    FROM public.activity_logs
    WHERE hotel_id = p_hotel_id
      AND action = 'night_audit_run'
      AND module = 'NIGHT_AUDIT'
    ORDER BY created_at DESC
    LIMIT 1;

    -- Get latest daily stats (yesterday's closed stats)
    SELECT revenue_room, occupancy_rate
    INTO v_stats
    FROM public.daily_hotel_stats
    WHERE hotel_id = p_hotel_id
    ORDER BY date DESC
    LIMIT 1;

    IF FOUND THEN
        v_today_revenue := v_stats.revenue_room;
        v_occupancy_rate := v_stats.occupancy_rate;
    END IF;

    -- Also add today's posted charges (current open day)
    SELECT COALESCE(SUM(ft.amount), 0) INTO v_today_revenue
    FROM public.folio_transactions ft
    WHERE ft.hotel_id = p_hotel_id
      AND ft.type = 'room_charge'
      AND ft.description = 'Daily room charge'
      AND ft.created_at::date = v_business_date - INTERVAL '1 day';

    RETURN jsonb_build_object(
        'business_date', v_business_date,
        'last_audit_at', v_last_audit_at,
        'revenue_today', v_today_revenue,
        'occupancy_rate', v_occupancy_rate
    );
END;
$$;

-- ============================================================
-- 8. pg_cron SCHEDULER
-- Runs every night at 02:00 for all active hotels
-- NOTE: pg_cron extension must be enabled in Supabase dashboard
-- ============================================================
DO $CRON$
DECLARE
    v_job_sql TEXT;
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_extension WHERE extname = 'pg_cron'
    ) THEN
        -- Remove existing job if present (ignore error if not found)
        BEGIN
            PERFORM cron.unschedule('night-audit-all-hotels');
        EXCEPTION WHEN OTHERS THEN
            NULL;
        END;

        -- Build job SQL as a plain text string (no nested dollar-quoting)
        v_job_sql := 'DO $BODY$ DECLARE v_hotel RECORD; BEGIN ' ||
                     'FOR v_hotel IN SELECT id FROM public.hotels LOOP ' ||
                     'BEGIN PERFORM public.run_night_audit(v_hotel.id); ' ||
                     'EXCEPTION WHEN OTHERS THEN ' ||
                     'INSERT INTO public.activity_logs(hotel_id, action, details, module) ' ||
                     'VALUES(v_hotel.id, ''night_audit_error'', ' ||
                     'jsonb_build_object(''error'', SQLERRM, ''source'', ''scheduler''), ' ||
                     '''NIGHT_AUDIT''); END; END LOOP; END; $BODY$';

        -- Schedule nightly 02:00 run
        PERFORM cron.schedule(
            'night-audit-all-hotels',
            '0 2 * * *',
            v_job_sql
        );

        RAISE NOTICE 'pg_cron: night-audit-all-hotels scheduled at 02:00 daily.';
    ELSE
        RAISE NOTICE 'pg_cron extension not found — scheduler skipped. Use Supabase Edge Function cron instead.';
    END IF;
END;
$CRON$;

-- ============================================================
-- DONE
-- ============================================================
